### ISSUE TITLE
Apres configuration de Jackett, impossible de recuperer les liens YggTorrent

### ISSUE THREAD

**Issue by Vivalemuc** [thcolin/sensorr#3]
J'ai bien installé et configuré Jackett sur mon serveur ;) Lorsque je lance une recherche manuelle sur Jackett, j'obtiens une liste de torrents disponible sur YggTorrent ;)

Cependant sensorr me retourne aucun résultat à chaque fois !

`vendors~main.bundle.js:23 Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at p (vendors~main.bundle.js:23)
    at o (vendors~main.bundle.js:16)
    at t.error (vendors~main.bundle.js:16)
    at t._error (vendors~main.bundle.js:16)
    at t.error (vendors~main.bundle.js:16)
    at t._error (vendors~main.bundle.js:16)
    at t.error (vendors~main.bundle.js:16)
    at t._error (vendors~main.bundle.js:16)
    at t.error (vendors~main.bundle.js:16)
    at t._error (vendors~main.bundle.js:16)`

`GET http://163.172.11.201:5070/proxy?url=aHR0cDovLzE2My4xNzIuMTEuMjAxOjkxMTcvYXBpL3YyLjAvaW5kZXhlcnMveWdndG9ycmVudC9yZXN1bHRzL3RvcnpuYWIvP3E9bGUgYnJpbyZRdWVyeT1sZSBicmlvJnQ9c2VhcmNoJmNhdD0yMDAwLDIwMTAsMjAyMCwyMDMwLDIwNDAsMjA1MCwyMDYwJmZvcm1hdD1qc29uJmFwaWtleT04dnJubmNlYTNhNGV3YzcwOWRoYTB1bnZma2x2OGEyag== 500 (Internal Server Error)`

`_ {message: "ajax error 500", name: "AjaxError", xhr: XMLHttpRequest, request: {…}, status: 500, …}`

**Comment by thcolin** [comment]
Peux ajouter le retour d'une requête `GET http://163.172.11.201:5070/proxy?url=aHR0cDovLzE2My4xNzIuMTEuMjAxOjkxMTcvYXBpL3YyLjAvaW5kZXhlcnMveWdndG9ycmVudC9yZXN1bHRzL3RvcnpuYWIvP3E9bGUgYnJpbyZRdWVyeT1sZSBicmlvJnQ9c2VhcmNoJmNhdD0yMDAwLDIwMTAsMjAyMCwyMDMwLDIwNDAsMjA1MCwyMDYwJmZvcm1hdD1qc29uJmFwaWtleT04dnJubmNlYTNhNGV3YzcwOWRoYTB1bnZma2x2OGEyag==` de ton navigateur s'il te plait ?

Hésite pas à caviarder tes informations personnels (clés de Jackett ou de tes trackers)

**Comment by Vivalemuc** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>

C'est l'erreur que j'obtiens !

**Comment by thcolin** [comment]
Ok, dans tes logs de serveur tu devrais avoir une entrée `PROXY [url]`, essaye d'accéder à `[url]` avec ton navigateur, il devrait te faire télécharger un fichier texte `api` si tout fonctionne bien, peux tu ajouter le contenu du fichier ?

**Comment by Vivalemuc** [comment]
Dans quel fichier de LOG cela devrait se situer ? Je ne trouve pas pour le moment :/

**Comment by thcolin** [comment]
La commande `npm run prod` affiche les logs en temps réel

**Comment by Vivalemuc** [comment]
Ca devrait t'aider !

`ReferenceError: URL is not defined
    at config.xznabs.some.xznab (/srv/seedbox/sensorr/index.js:65:71)
    at Array.some (<anonymous>)
    at /srv/seedbox/sensorr/index.js:65:21
    at Layer.handle [as handle_request] (/srv/seedbox/sensorr/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/seedbox/sensorr/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/srv/seedbox/sensorr/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/srv/seedbox/sensorr/node_modules/express/lib/router/layer.js:95:5)
    at /srv/seedbox/sensorr/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:335:12)
    at next (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:275:10)
    at authMiddleware (/srv/seedbox/sensorr/node_modules/express-basic-auth/index.js:49:16)
    at Layer.handle [as handle_request] (/srv/seedbox/sensorr/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:317:13)
    at /srv/seedbox/sensorr/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:335:12)
    at next (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:275:10)
`

**Comment by thcolin** [comment]
C'est ta configuration qui à un soucis, elle devrait ressembler à : 
```
{
  ...
  "xznabs": [
    {
      "name": "Jackett (YGG)",
      "url": "http://localhost:9117/api/v2.0/indexers/yggtorrent/results/torznab/api",
      "key": "x"
    }
  ],
  ...
}
```

**Comment by Vivalemuc** [comment]
"xznabs": [
    {
      "name": "YGGtorrent",
      "url": "http://ip:9117/api/v2.0/indexers/yggtorrent/results/torznab/",
      "key": "x",
      "disabled": false
    }
  ],

**Comment by Vivalemuc** [comment]
`ReferenceError: document is not defined
    at new URL (/srv/seedbox/sensorr/node_modules/url-polyfill/url-polyfill.js:268:17)
    at config.xznabs.some.xznab (/srv/seedbox/sensorr/index.js:67:67)
    at Array.some (<anonymous>)
    at /srv/seedbox/sensorr/index.js:67:21
    at Layer.handle [as handle_request] (/srv/seedbox/sensorr/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/seedbox/sensorr/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/srv/seedbox/sensorr/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/srv/seedbox/sensorr/node_modules/express/lib/router/layer.js:95:5)
    at /srv/seedbox/sensorr/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:335:12)
    at next (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:275:10)
    at authMiddleware (/srv/seedbox/sensorr/node_modules/express-basic-auth/index.js:49:16)
    at Layer.handle [as handle_request] (/srv/seedbox/sensorr/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:317:13)
    at /srv/seedbox/sensorr/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/srv/seedbox/sensorr/node_modules/express/lib/router/index.js:335:12)
`

On doit s'en rapprocher ^^

**Comment by thcolin** [comment]
Quelle version de Node utilise tu ?

**Comment by Vivalemuc** [comment]
Node v8.14.0

Je peux essayer de l'update mais j'ai tellement galere pour Flood que je prefere eviter :)

**Comment by thcolin** [comment]
Je viens de tester avec Node `v8.14.0` et ça devrait le faire avec le dernier commit, pense à pull `master`

**Comment by Vivalemuc** [comment]
Je te dis, je te remercie ;)

**Comment by Vivalemuc** [comment]
Ca y est ca fonctionne :) Merci ;)

Du coup des que je passe un film en wishlist, il sera download automatiquement des qu'il sera sur le tracker c'est ca ?

**Comment by thcolin** [comment]
Yes, chaque soir à 17h si la timezone du serveur est correctement configuré

**Comment by Vivalemuc** [comment]
Au pire si l'heure n'est pas bien configuré c'est pas grave ;)

Et il prendra la version suivant les filtres si j'ai bien compris ? Et celle avec le plus de seeders si plusieurs résultats ?

**Comment by thcolin** [comment]
Exactement, la configuration par défaut pour l'ordre étant `seeders`, mais tu peux la modifier pour `seeders`, `peers` (`seeders` + `leechers`) et `size`

**Comment by Vivalemuc** [comment]
Le top du top serait de pouvoir dire prendre 1080p si différence avec 720p inférieur à 1 go ;)

Car si je peux éviter de DL un 1080p a 8go plutot qu'un 720 à 2.5go ce serait l'ideal, mais ca me semble complexe à mettre en place !

**Comment by thcolin** [comment]
Je préfère garder la configuration simple pour l'instant, la priorisation des filtres arrivera surement dans un second temps

**Comment by Vivalemuc** [comment]
Je comprends totalement ;)

Derniere question, une version sur les séries est prevus ? Ou tu reste sur les films seulement ?

**Comment by thcolin** [comment]
Uniquement les films, je n'ai pas le besoin personnel pour les séries, j'aurais du mal à le maintenir au quotidien

**Comment by Vivalemuc** [comment]
C'est dommage car le principe est le même plus ou moins ;)
Il suffit de récupérer un annuaire de serie et aller chercher le fichier correspondant je pense ;)

**Comment by thcolin** [comment]
Je doute que TVDB ait une API aussi simple et pratique que TMDB, de plus cela apporte d'autres contraintes comme le fait de rafraichir les données de la série (savoir si elle est canceled) ou encore de suivre le dernier épisode téléchargé
